Draft of script workflow in README

diff --git a/dotcp-merge-bases b/dotcp-merge-bases
--- a/dotcp-merge-bases
+++ b/dotcp-merge-bases
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-# Merge all base branches into master
+# Merge all base branches into master. Use this to distribute changes made on
+# one machine to all others.
 
 set -eu
 
@@ -13,5 +14,7 @@ git checkout $master_branch
 
 for base_branch in $(git branch --format='%(refname:short)' | grep 'base-'); do
     git checkout $base_branch
-    git merge $master_branch
+    # XXX with set -e, this may fail too early (b4 we visited all branches) if
+    # we use --ff-only and ff is not possible
+    git merge $@ $master_branch
 done
